# Generated by Django 5.0.6 on 2024-06-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=50)),
                ("categoria", models.CharField(default="", max_length=50)),
                ("stock", models.IntegerField(default=0)),
                ("precio", models.IntegerField(default=0)),
            ],
        ),
    ]
