# Generated by Django 5.0.6 on 2024-06-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superApp", "0002_producto_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
