# Generated by Django 5.0.6 on 2024-07-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superApp", "0003_alter_producto_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_consulta", models.CharField(default="", max_length=100)),
                ("correo_electronico", models.EmailField(default="", max_length=100)),
                ("imagen", models.ImageField(upload_to="images/")),
                ("telefono", models.IntegerField(default=0)),
                ("descripcion", models.CharField(default="", max_length=500)),
            ],
        ),
    ]
