# Generated by Django 5.0.6 on 2024-07-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("superApp", "0004_formulario"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="estado",
            field=models.CharField(default="", max_length=100),
        ),
    ]
